# Generated by Django 3.1.3 on 2022-04-19 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20220413_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorinfo',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
